services:
  app:
    build: .
    container_name: walletwatcher-app
    restart: always
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/wallet_db?schema=public
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    container_name: local-postgres-walletwatcher
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: